apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: regionchecker
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - cronjob.yaml
commonLabels:
  app.kubernetes.io/name: regionchecker
  app.kubernetes.io/part-of: regionchecker
images:
  - name: ghcr.io/binsarjr/regionchecker
    newTag: latest
