apiVersion: v1
kind: Service
metadata:
  name: regionchecker
  namespace: regionchecker
  labels:
    app.kubernetes.io/name: regionchecker
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: regionchecker
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
