package domain

import "strings"

// geoGTLDMap maps geographic gTLDs to ISO 3166-1 alpha-2 codes.
var geoGTLDMap = map[string]string{
	"tokyo":      "JP",
	"kyoto":      "JP",
	"nagoya":     "JP",
	"osaka":      "JP",
	"yokohama":   "JP",
	"berlin":     "DE",
	"hamburg":    "DE",
	"koeln":      "DE",
	"cologne":    "DE",
	"bayern":     "DE",
	"nrw":        "DE",
	"ruhr":       "DE",
	"saarland":   "DE",
	"london":     "GB",
	"scot":       "GB",
	"wales":      "GB",
	"cymru":      "GB",
	"paris":      "FR",
	"alsace":     "FR",
	"bzh":        "FR",
	"corsica":    "FR",
	"nyc":        "US",
	"vegas":      "US",
	"miami":      "US",
	"boston":     "US",
	"lat":        "US",
	"moscow":     "RU",
	"tatar":      "RU",
	"amsterdam":  "NL",
	"frl":        "NL",
	"barcelona":  "ES",
	"madrid":     "ES",
	"bcn":        "ES",
	"gal":        "ES",
	"eus":        "ES",
	"istanbul":   "TR",
	"brussels":   "BE",
	"vlaanderen": "BE",
	"gent":       "BE",
	"wien":       "AT",
	"tirol":      "AT",
	"quebec":     "CA",
	"melbourne":  "AU",
	"sydney":     "AU",
	"dubai":      "AE",
	"abudhabi":   "AE",
	"capetown":   "ZA",
	"durban":     "ZA",
	"joburg":     "ZA",
	"rio":        "BR",
	"saarland2":  "DE",
	"budapest":   "HU",
	"helsinki":   "FI",
	"stockholm":  "SE",
	"zuerich":    "CH",
	"swiss":      "CH",
	"taipei":     "TW",
	"seoul":      "KR",
	"okinawa":    "JP",
	"ryukyu":     "JP",
}

// GeoCountry returns the country code for a geographic gTLD.
func GeoCountry(tld string) (string, bool) {
	cc, ok := geoGTLDMap[strings.ToLower(tld)]
	return cc, ok
}
